; Extensiones necesarias para Lector de Resoluciones
extension_dir = "ext"
extension=zip
extension=mbstring
extension=gd
extension=fileinfo
extension=pdo_pgsql
extension=pgsql

; Limites de subida aumentados para PDFs grandes
upload_max_filesize=50M
post_max_size=50M
